### ISSUE TITLE
Documentation Request: examples

### ISSUE THREAD

**Issue by ballPointPenguin** [gatemedia/ember-qunit-mock#1]
I'm not quite sure how to use this library.
It would be really great to see some examples in the README.
For instance, what exactly is 'MockName'?
What if I am just mocking a single method and not a method on an object?
What if I am trying to mock a method within a method?
How much of sinon.js api is replicated by this library (e.g. "stub")?

**Comment by MikeAski** [comment]
Hi @ballPointPenguin, and welcome to this project.

I will add some doc & try to explicit more semantics ASAP.

About your 2nd question, this project only aims at mocking Ember Object methods, so it does not support mocking a single method.
Mocking a method inside another method is not supported, but if this inner call is handled by an object, you could achieve it by mocking the inner method and passing the mock to the outer method.

Sinon.js API is partially implemented, as I implemented only use cases that I was directly needed for the moment. Any PR is welcome :+1:

**Comment by ballPointPenguin** [comment]
Thanks for the reply @MikeAski. It looks like I'll be using mocha & chai for my current project after all.
However, I am a big fan of all things ember+testing so I'll keep on eye on this cool addon and maybe be able to lend a hand in the future.
